#!/bin/bash

if [ $# = 0 ] || [ $1 = "-h" ]
then
	echo "Usage:"
	echo -e "\textract-vmlinux [File]\n"
	echo -e "Set [File] to packed kernel image file\n"
	exit 0
fi

/usr/src/linux-headers-$(uname -r)/scripts/extract-vmlinux "$1" > vmlinux
