#!/bin/bash

if [ $# = 0 ] || [ $1 = "-h" ]
then
	echo "Usage:"
	echo -e "\tunpack-cpio [File]\n"
	echo -e "Set [File] to vmlinux file\n"
	exit 0
fi


mkdir rootfs
cp "$1" ./rootfs
cd ./rootfs
cpio -id -v < "$1"
rm $1
